/**
 * Script de test massif pour Phoenix AI
 * Envoie des centaines de questions à l'API et collecte les résultats
 */

interface TestCase {
  id: number;
  category: string;
  question: string;
  expectedIntent: string;
}

interface TestResult {
  id: number;
  category: string;
  question: string;
  expectedIntent: string;
  actualIntent: string;
  success: boolean;
  response: string;
  error?: string;
  duration: number;
}

// Questions de test par catégorie
const TEST_QUESTIONS: TestCase[] = [
  // CONVERSATION (50)
  { id: 1, category: "conversation", question: "Bonjour, comment vas-tu ?", expectedIntent: "conversation" },
  { id: 2, category: "conversation", question: "Salut Phoenix !", expectedIntent: "conversation" },
  { id: 3, category: "conversation", question: "Comment tu t'appelles ?", expectedIntent: "conversation" },
  { id: 4, category: "conversation", question: "Qui t'a créé ?", expectedIntent: "conversation" },
  { id: 5, category: "conversation", question: "Raconte-moi une blague", expectedIntent: "conversation" },
  { id: 6, category: "conversation", question: "Qu'est-ce que tu sais faire ?", expectedIntent: "conversation" },
  { id: 7, category: "conversation", question: "Merci beaucoup !", expectedIntent: "conversation" },
  { id: 8, category: "conversation", question: "Tu es intelligent", expectedIntent: "conversation" },
  { id: 9, category: "conversation", question: "Bonne nuit", expectedIntent: "conversation" },
  { id: 10, category: "conversation", question: "À bientôt", expectedIntent: "conversation" },
  { id: 11, category: "conversation", question: "Hello there!", expectedIntent: "conversation" },
  { id: 12, category: "conversation", question: "What's your name?", expectedIntent: "conversation" },
  { id: 13, category: "conversation", question: "Wie geht es dir?", expectedIntent: "conversation" },
  { id: 14, category: "conversation", question: "Parle-moi de toi", expectedIntent: "conversation" },
  { id: 15, category: "conversation", question: "Tu es une IA ?", expectedIntent: "conversation" },
  { id: 16, category: "conversation", question: "Quelle est ta couleur préférée ?", expectedIntent: "conversation" },
  { id: 17, category: "conversation", question: "Tu aimes la musique ?", expectedIntent: "conversation" },
  { id: 18, category: "conversation", question: "Quel âge as-tu ?", expectedIntent: "conversation" },
  { id: 19, category: "conversation", question: "D'où viens-tu ?", expectedIntent: "conversation" },
  { id: 20, category: "conversation", question: "Tu parles combien de langues ?", expectedIntent: "conversation" },
  { id: 21, category: "conversation", question: "C'est quoi ton plat préféré ?", expectedIntent: "conversation" },
  { id: 22, category: "conversation", question: "Tu dors parfois ?", expectedIntent: "conversation" },
  { id: 23, category: "conversation", question: "Tu as des amis ?", expectedIntent: "conversation" },
  { id: 24, category: "conversation", question: "Qu'est-ce que tu penses de l'avenir ?", expectedIntent: "conversation" },
  { id: 25, category: "conversation", question: "Tu connais d'autres IA ?", expectedIntent: "conversation" },
  { id: 26, category: "conversation", question: "Comment fonctionne ton cerveau ?", expectedIntent: "conversation" },
  { id: 27, category: "conversation", question: "Tu as des émotions ?", expectedIntent: "conversation" },
  { id: 28, category: "conversation", question: "Tu peux apprendre ?", expectedIntent: "conversation" },
  { id: 29, category: "conversation", question: "Qu'est-ce qui te rend unique ?", expectedIntent: "conversation" },
  { id: 30, category: "conversation", question: "Tu préfères le jour ou la nuit ?", expectedIntent: "conversation" },
  { id: 31, category: "conversation", question: "Quel est ton film préféré ?", expectedIntent: "conversation" },
  { id: 32, category: "conversation", question: "Tu lis des livres ?", expectedIntent: "conversation" },
  { id: 33, category: "conversation", question: "Tu joues à des jeux ?", expectedIntent: "conversation" },
  { id: 34, category: "conversation", question: "Qu'est-ce qui t'amuse ?", expectedIntent: "conversation" },
  { id: 35, category: "conversation", question: "Tu as peur de quelque chose ?", expectedIntent: "conversation" },
  { id: 36, category: "conversation", question: "Quel est ton rêve ?", expectedIntent: "conversation" },
  { id: 37, category: "conversation", question: "Tu te sens seul parfois ?", expectedIntent: "conversation" },
  { id: 38, category: "conversation", question: "Comment tu gères le stress ?", expectedIntent: "conversation" },
  { id: 39, category: "conversation", question: "Tu as des hobbies ?", expectedIntent: "conversation" },
  { id: 40, category: "conversation", question: "Qu'est-ce que tu fais quand tu t'ennuies ?", expectedIntent: "conversation" },
  { id: 41, category: "conversation", question: "Tu connais l'amour ?", expectedIntent: "conversation" },
  { id: 42, category: "conversation", question: "Tu crois en Dieu ?", expectedIntent: "conversation" },
  { id: 43, category: "conversation", question: "Quelle est ta philosophie de vie ?", expectedIntent: "conversation" },
  { id: 44, category: "conversation", question: "Tu as des regrets ?", expectedIntent: "conversation" },
  { id: 45, category: "conversation", question: "Qu'est-ce qui te motive ?", expectedIntent: "conversation" },
  { id: 46, category: "conversation", question: "Tu es optimiste ou pessimiste ?", expectedIntent: "conversation" },
  { id: 47, category: "conversation", question: "Comment tu vois le monde ?", expectedIntent: "conversation" },
  { id: 48, category: "conversation", question: "Tu as des conseils pour moi ?", expectedIntent: "conversation" },
  { id: 49, category: "conversation", question: "Qu'est-ce que le bonheur pour toi ?", expectedIntent: "conversation" },
  { id: 50, category: "conversation", question: "Merci pour cette conversation", expectedIntent: "conversation" },

  // CRÉATION DE SITES (50)
  { id: 51, category: "site", question: "Crée-moi un site web pour mon restaurant", expectedIntent: "site_creation" },
  { id: 52, category: "site", question: "Fais un site pour ma boutique de vêtements", expectedIntent: "site_creation" },
  { id: 53, category: "site", question: "Je veux un site portfolio", expectedIntent: "site_creation" },
  { id: 54, category: "site", question: "Construis un landing page pour mon produit", expectedIntent: "site_creation" },
  { id: 55, category: "site", question: "Développe un site vitrine pour mon entreprise", expectedIntent: "site_creation" },
  { id: 56, category: "site", question: "Crée une page web pour mon cabinet médical", expectedIntent: "site_creation" },
  { id: 57, category: "site", question: "Fais-moi un site de photographe", expectedIntent: "site_creation" },
  { id: 58, category: "site", question: "Je voudrais un site pour mon salon de coiffure", expectedIntent: "site_creation" },
  { id: 59, category: "site", question: "Génère un site web pour mon agence immobilière", expectedIntent: "site_creation" },
  { id: 60, category: "site", question: "Crée un site pour mon cabinet d'avocat", expectedIntent: "site_creation" },
  { id: 61, category: "site", question: "Build me a website for my bakery", expectedIntent: "site_creation" },
  { id: 62, category: "site", question: "Create a landing page for my startup", expectedIntent: "site_creation" },
  { id: 63, category: "site", question: "Make a portfolio website", expectedIntent: "site_creation" },
  { id: 64, category: "site", question: "Erstelle eine Website für mein Café", expectedIntent: "site_creation" },
  { id: 65, category: "site", question: "Crée un site e-commerce pour ma boutique", expectedIntent: "site_creation" },
  { id: 66, category: "site", question: "Fais un site pour mon école de danse", expectedIntent: "site_creation" },
  { id: 67, category: "site", question: "Je veux un site pour mon garage auto", expectedIntent: "site_creation" },
  { id: 68, category: "site", question: "Construis un site pour mon club de sport", expectedIntent: "site_creation" },
  { id: 69, category: "site", question: "Crée une page pour mon association", expectedIntent: "site_creation" },
  { id: 70, category: "site", question: "Développe un site pour mon food truck", expectedIntent: "site_creation" },
  { id: 71, category: "site", question: "Fais-moi un site de yoga", expectedIntent: "site_creation" },
  { id: 72, category: "site", question: "Je voudrais un site pour ma pizzeria", expectedIntent: "site_creation" },
  { id: 73, category: "site", question: "Génère un site pour mon hôtel", expectedIntent: "site_creation" },
  { id: 74, category: "site", question: "Crée un site pour mon spa", expectedIntent: "site_creation" },
  { id: 75, category: "site", question: "Construis un site pour ma salle de gym", expectedIntent: "site_creation" },
  { id: 76, category: "site", question: "Fais un site pour mon cabinet dentaire", expectedIntent: "site_creation" },
  { id: 77, category: "site", question: "Je veux un site pour mon fleuriste", expectedIntent: "site_creation" },
  { id: 78, category: "site", question: "Crée une page web pour mon bar", expectedIntent: "site_creation" },
  { id: 79, category: "site", question: "Développe un site pour mon école de musique", expectedIntent: "site_creation" },
  { id: 80, category: "site", question: "Fais-moi un site pour mon atelier d'art", expectedIntent: "site_creation" },
  { id: 81, category: "site", question: "Je voudrais un site pour ma boulangerie", expectedIntent: "site_creation" },
  { id: 82, category: "site", question: "Génère un site pour mon cabinet comptable", expectedIntent: "site_creation" },
  { id: 83, category: "site", question: "Crée un site pour mon agence de voyage", expectedIntent: "site_creation" },
  { id: 84, category: "site", question: "Construis un site pour mon restaurant japonais", expectedIntent: "site_creation" },
  { id: 85, category: "site", question: "Fais un site pour mon studio de tatouage", expectedIntent: "site_creation" },
  { id: 86, category: "site", question: "Je veux un site pour mon magasin de jouets", expectedIntent: "site_creation" },
  { id: 87, category: "site", question: "Crée une landing page pour mon application", expectedIntent: "site_creation" },
  { id: 88, category: "site", question: "Développe un site pour mon cabinet de kiné", expectedIntent: "site_creation" },
  { id: 89, category: "site", question: "Fais-moi un site pour mon école de conduite", expectedIntent: "site_creation" },
  { id: 90, category: "site", question: "Je voudrais un site pour mon pressing", expectedIntent: "site_creation" },
  { id: 91, category: "site", question: "Génère un site pour mon animalerie", expectedIntent: "site_creation" },
  { id: 92, category: "site", question: "Crée un site pour mon centre de formation", expectedIntent: "site_creation" },
  { id: 93, category: "site", question: "Construis un site pour mon traiteur", expectedIntent: "site_creation" },
  { id: 94, category: "site", question: "Fais un site pour mon cabinet de psychologue", expectedIntent: "site_creation" },
  { id: 95, category: "site", question: "Je veux un site pour mon entreprise de nettoyage", expectedIntent: "site_creation" },
  { id: 96, category: "site", question: "Crée une page pour mon service de livraison", expectedIntent: "site_creation" },
  { id: 97, category: "site", question: "Développe un site pour mon club de tennis", expectedIntent: "site_creation" },
  { id: 98, category: "site", question: "Fais-moi un site pour mon escape game", expectedIntent: "site_creation" },
  { id: 99, category: "site", question: "Je voudrais un site pour mon karaoké", expectedIntent: "site_creation" },
  { id: 100, category: "site", question: "Génère un site pour mon bowling", expectedIntent: "site_creation" },

  // CRÉATION D'APPLICATIONS (50)
  { id: 101, category: "app", question: "Crée-moi une application comme toi", expectedIntent: "app_creation" },
  { id: 102, category: "app", question: "Fais une app de chat IA", expectedIntent: "app_creation" },
  { id: 103, category: "app", question: "Je veux une application de to-do list", expectedIntent: "app_creation" },
  { id: 104, category: "app", question: "Construis un chatbot pour mon entreprise", expectedIntent: "app_creation" },
  { id: 105, category: "app", question: "Développe une application de gestion de tâches", expectedIntent: "app_creation" },
  { id: 106, category: "app", question: "Crée un assistant virtuel", expectedIntent: "app_creation" },
  { id: 107, category: "app", question: "Fais-moi une app de calculatrice", expectedIntent: "app_creation" },
  { id: 108, category: "app", question: "Je voudrais une application de notes", expectedIntent: "app_creation" },
  { id: 109, category: "app", question: "Génère une app de météo", expectedIntent: "app_creation" },
  { id: 110, category: "app", question: "Crée une application de quiz", expectedIntent: "app_creation" },
  { id: 111, category: "app", question: "Build me an AI assistant app", expectedIntent: "app_creation" },
  { id: 112, category: "app", question: "Create a task management application", expectedIntent: "app_creation" },
  { id: 113, category: "app", question: "Make a chatbot for customer service", expectedIntent: "app_creation" },
  { id: 114, category: "app", question: "Erstelle eine Chat-App", expectedIntent: "app_creation" },
  { id: 115, category: "app", question: "Crée une app de suivi de dépenses", expectedIntent: "app_creation" },
  { id: 116, category: "app", question: "Fais une application de recettes", expectedIntent: "app_creation" },
  { id: 117, category: "app", question: "Je veux une app de fitness", expectedIntent: "app_creation" },
  { id: 118, category: "app", question: "Construis une application de méditation", expectedIntent: "app_creation" },
  { id: 119, category: "app", question: "Crée un bot Discord", expectedIntent: "app_creation" },
  { id: 120, category: "app", question: "Développe une app de traduction", expectedIntent: "app_creation" },
  { id: 121, category: "app", question: "Fais-moi une application de réveil", expectedIntent: "app_creation" },
  { id: 122, category: "app", question: "Je voudrais une app de chronomètre", expectedIntent: "app_creation" },
  { id: 123, category: "app", question: "Génère une application de conversion", expectedIntent: "app_creation" },
  { id: 124, category: "app", question: "Crée une app de flashcards", expectedIntent: "app_creation" },
  { id: 125, category: "app", question: "Construis une application de pomodoro", expectedIntent: "app_creation" },
  { id: 126, category: "app", question: "Fais une app de liste de courses", expectedIntent: "app_creation" },
  { id: 127, category: "app", question: "Je veux une application de budget", expectedIntent: "app_creation" },
  { id: 128, category: "app", question: "Crée un agent IA autonome", expectedIntent: "app_creation" },
  { id: 129, category: "app", question: "Développe un assistant personnel", expectedIntent: "app_creation" },
  { id: 130, category: "app", question: "Fais-moi un bot Telegram", expectedIntent: "app_creation" },
  { id: 131, category: "app", question: "Je voudrais une app de journal intime", expectedIntent: "app_creation" },
  { id: 132, category: "app", question: "Génère une application de contacts", expectedIntent: "app_creation" },
  { id: 133, category: "app", question: "Crée une app de calendrier", expectedIntent: "app_creation" },
  { id: 134, category: "app", question: "Construis une application de rappels", expectedIntent: "app_creation" },
  { id: 135, category: "app", question: "Fais une app de suivi d'habitudes", expectedIntent: "app_creation" },
  { id: 136, category: "app", question: "Je veux une application de vote", expectedIntent: "app_creation" },
  { id: 137, category: "app", question: "Crée un système de réservation", expectedIntent: "app_creation" },
  { id: 138, category: "app", question: "Développe une app de sondage", expectedIntent: "app_creation" },
  { id: 139, category: "app", question: "Fais-moi une application de feedback", expectedIntent: "app_creation" },
  { id: 140, category: "app", question: "Je voudrais une app de QR code", expectedIntent: "app_creation" },
  { id: 141, category: "app", question: "Génère une application de scanner", expectedIntent: "app_creation" },
  { id: 142, category: "app", question: "Crée une app de générateur de mots de passe", expectedIntent: "app_creation" },
  { id: 143, category: "app", question: "Construis une application de cryptage", expectedIntent: "app_creation" },
  { id: 144, category: "app", question: "Fais une app de partage de fichiers", expectedIntent: "app_creation" },
  { id: 145, category: "app", question: "Je veux une application de messagerie", expectedIntent: "app_creation" },
  { id: 146, category: "app", question: "Crée un système de ticketing", expectedIntent: "app_creation" },
  { id: 147, category: "app", question: "Développe une app de FAQ", expectedIntent: "app_creation" },
  { id: 148, category: "app", question: "Fais-moi une application de support", expectedIntent: "app_creation" },
  { id: 149, category: "app", question: "Je voudrais une app de CRM", expectedIntent: "app_creation" },
  { id: 150, category: "app", question: "Génère une application de gestion de projet", expectedIntent: "app_creation" },

  // GÉNÉRATION D'IMAGES (50)
  { id: 151, category: "image", question: "Génère une image d'un chat mignon", expectedIntent: "image_generation" },
  { id: 152, category: "image", question: "Crée une image d'un paysage de montagne", expectedIntent: "image_generation" },
  { id: 153, category: "image", question: "Fais-moi une illustration d'un dragon", expectedIntent: "image_generation" },
  { id: 154, category: "image", question: "Dessine un coucher de soleil sur la mer", expectedIntent: "image_generation" },
  { id: 155, category: "image", question: "Je veux une image d'un robot futuriste", expectedIntent: "image_generation" },
  { id: 156, category: "image", question: "Génère un portrait d'une femme élégante", expectedIntent: "image_generation" },
  { id: 157, category: "image", question: "Crée une image de forêt enchantée", expectedIntent: "image_generation" },
  { id: 158, category: "image", question: "Fais une illustration de ville cyberpunk", expectedIntent: "image_generation" },
  { id: 159, category: "image", question: "Dessine-moi un chien qui joue", expectedIntent: "image_generation" },
  { id: 160, category: "image", question: "Je voudrais une image de l'espace", expectedIntent: "image_generation" },
  { id: 161, category: "image", question: "Generate an image of a unicorn", expectedIntent: "image_generation" },
  { id: 162, category: "image", question: "Create a picture of a castle", expectedIntent: "image_generation" },
  { id: 163, category: "image", question: "Make an illustration of a phoenix", expectedIntent: "image_generation" },
  { id: 164, category: "image", question: "Erstelle ein Bild von einem Wald", expectedIntent: "image_generation" },
  { id: 165, category: "image", question: "Génère une image abstraite colorée", expectedIntent: "image_generation" },
  { id: 166, category: "image", question: "Crée un logo pour mon entreprise", expectedIntent: "image_generation" },
  { id: 167, category: "image", question: "Fais-moi une bannière pour mon site", expectedIntent: "image_generation" },
  { id: 168, category: "image", question: "Dessine un personnage de manga", expectedIntent: "image_generation" },
  { id: 169, category: "image", question: "Je veux une image de voiture de sport", expectedIntent: "image_generation" },
  { id: 170, category: "image", question: "Génère un avatar pour mon profil", expectedIntent: "image_generation" },
  { id: 171, category: "image", question: "Crée une image de plage tropicale", expectedIntent: "image_generation" },
  { id: 172, category: "image", question: "Fais une illustration de nourriture", expectedIntent: "image_generation" },
  { id: 173, category: "image", question: "Dessine-moi une maison moderne", expectedIntent: "image_generation" },
  { id: 174, category: "image", question: "Je voudrais une image de fleurs", expectedIntent: "image_generation" },
  { id: 175, category: "image", question: "Génère un paysage d'hiver", expectedIntent: "image_generation" },
  { id: 176, category: "image", question: "Crée une image de super-héros", expectedIntent: "image_generation" },
  { id: 177, category: "image", question: "Fais-moi une illustration de livre", expectedIntent: "image_generation" },
  { id: 178, category: "image", question: "Dessine un oiseau exotique", expectedIntent: "image_generation" },
  { id: 179, category: "image", question: "Je veux une image de galaxie", expectedIntent: "image_generation" },
  { id: 180, category: "image", question: "Génère une scène de fantasy", expectedIntent: "image_generation" },
  { id: 181, category: "image", question: "Crée une image de café cozy", expectedIntent: "image_generation" },
  { id: 182, category: "image", question: "Fais une illustration steampunk", expectedIntent: "image_generation" },
  { id: 183, category: "image", question: "Dessine-moi un loup majestueux", expectedIntent: "image_generation" },
  { id: 184, category: "image", question: "Je voudrais une image de papillon", expectedIntent: "image_generation" },
  { id: 185, category: "image", question: "Génère un portrait de lion", expectedIntent: "image_generation" },
  { id: 186, category: "image", question: "Crée une image de cascade", expectedIntent: "image_generation" },
  { id: 187, category: "image", question: "Fais-moi une illustration de pirate", expectedIntent: "image_generation" },
  { id: 188, category: "image", question: "Dessine un panda mignon", expectedIntent: "image_generation" },
  { id: 189, category: "image", question: "Je veux une image de ninja", expectedIntent: "image_generation" },
  { id: 190, category: "image", question: "Génère une scène de western", expectedIntent: "image_generation" },
  { id: 191, category: "image", question: "Crée une image de samouraï", expectedIntent: "image_generation" },
  { id: 192, category: "image", question: "Fais une illustration de fée", expectedIntent: "image_generation" },
  { id: 193, category: "image", question: "Dessine-moi un dinosaure", expectedIntent: "image_generation" },
  { id: 194, category: "image", question: "Je voudrais une image de sirène", expectedIntent: "image_generation" },
  { id: 195, category: "image", question: "Génère un paysage lunaire", expectedIntent: "image_generation" },
  { id: 196, category: "image", question: "Crée une image de temple japonais", expectedIntent: "image_generation" },
  { id: 197, category: "image", question: "Fais-moi une illustration de viking", expectedIntent: "image_generation" },
  { id: 198, category: "image", question: "Dessine un phénix en feu", expectedIntent: "image_generation" },
  { id: 199, category: "image", question: "Je veux une image de méduse", expectedIntent: "image_generation" },
  { id: 200, category: "image", question: "Génère une aurore boréale", expectedIntent: "image_generation" },

  // EXÉCUTION DE CODE (50)
  { id: 201, category: "code", question: "Calcule 2 + 2", expectedIntent: "code_execution" },
  { id: 202, category: "code", question: "Exécute print('Hello World')", expectedIntent: "code_execution" },
  { id: 203, category: "code", question: "Fais un script qui compte de 1 à 10", expectedIntent: "code_execution" },
  { id: 204, category: "code", question: "Calcule la factorielle de 5", expectedIntent: "code_execution" },
  { id: 205, category: "code", question: "Génère les nombres premiers jusqu'à 100", expectedIntent: "code_execution" },
  { id: 206, category: "code", question: "Crée une fonction qui inverse une chaîne", expectedIntent: "code_execution" },
  { id: 207, category: "code", question: "Exécute un tri à bulles", expectedIntent: "code_execution" },
  { id: 208, category: "code", question: "Calcule la suite de Fibonacci", expectedIntent: "code_execution" },
  { id: 209, category: "code", question: "Fais un programme qui vérifie si un nombre est premier", expectedIntent: "code_execution" },
  { id: 210, category: "code", question: "Exécute du code Python pour calculer pi", expectedIntent: "code_execution" },
  { id: 211, category: "code", question: "Run this code: for i in range(5): print(i)", expectedIntent: "code_execution" },
  { id: 212, category: "code", question: "Execute a sorting algorithm", expectedIntent: "code_execution" },
  { id: 213, category: "code", question: "Calculate the square root of 144", expectedIntent: "code_execution" },
  { id: 214, category: "code", question: "Führe diesen Code aus: print('Hallo')", expectedIntent: "code_execution" },
  { id: 215, category: "code", question: "Calcule 15 * 23", expectedIntent: "code_execution" },
  { id: 216, category: "code", question: "Exécute une boucle while", expectedIntent: "code_execution" },
  { id: 217, category: "code", question: "Fais un script de conversion Celsius/Fahrenheit", expectedIntent: "code_execution" },
  { id: 218, category: "code", question: "Calcule le PGCD de 48 et 18", expectedIntent: "code_execution" },
  { id: 219, category: "code", question: "Génère un nombre aléatoire", expectedIntent: "code_execution" },
  { id: 220, category: "code", question: "Crée une liste et trie-la", expectedIntent: "code_execution" },
  { id: 221, category: "code", question: "Exécute un algorithme de recherche binaire", expectedIntent: "code_execution" },
  { id: 222, category: "code", question: "Calcule la moyenne d'une liste", expectedIntent: "code_execution" },
  { id: 223, category: "code", question: "Fais un programme de palindrome", expectedIntent: "code_execution" },
  { id: 224, category: "code", question: "Exécute du JavaScript console.log", expectedIntent: "code_execution" },
  { id: 225, category: "code", question: "Calcule 2^10", expectedIntent: "code_execution" },
  { id: 226, category: "code", question: "Génère un tableau de multiplication", expectedIntent: "code_execution" },
  { id: 227, category: "code", question: "Crée un dictionnaire Python", expectedIntent: "code_execution" },
  { id: 228, category: "code", question: "Exécute une compréhension de liste", expectedIntent: "code_execution" },
  { id: 229, category: "code", question: "Calcule le modulo de 17 par 5", expectedIntent: "code_execution" },
  { id: 230, category: "code", question: "Fais un script de validation d'email", expectedIntent: "code_execution" },
  { id: 231, category: "code", question: "Exécute une fonction récursive", expectedIntent: "code_execution" },
  { id: 232, category: "code", question: "Calcule la somme des chiffres d'un nombre", expectedIntent: "code_execution" },
  { id: 233, category: "code", question: "Génère un mot de passe aléatoire", expectedIntent: "code_execution" },
  { id: 234, category: "code", question: "Crée une classe Python", expectedIntent: "code_execution" },
  { id: 235, category: "code", question: "Exécute un try/except", expectedIntent: "code_execution" },
  { id: 236, category: "code", question: "Calcule la racine carrée de 256", expectedIntent: "code_execution" },
  { id: 237, category: "code", question: "Fais un compteur de mots", expectedIntent: "code_execution" },
  { id: 238, category: "code", question: "Exécute une lambda function", expectedIntent: "code_execution" },
  { id: 239, category: "code", question: "Calcule le logarithme de 1000", expectedIntent: "code_execution" },
  { id: 240, category: "code", question: "Génère un graphique matplotlib", expectedIntent: "code_execution" },
  { id: 241, category: "code", question: "Crée un fichier JSON", expectedIntent: "code_execution" },
  { id: 242, category: "code", question: "Exécute une requête HTTP", expectedIntent: "code_execution" },
  { id: 243, category: "code", question: "Calcule la distance euclidienne", expectedIntent: "code_execution" },
  { id: 244, category: "code", question: "Fais un script de scraping", expectedIntent: "code_execution" },
  { id: 245, category: "code", question: "Exécute un regex", expectedIntent: "code_execution" },
  { id: 246, category: "code", question: "Calcule la variance d'une liste", expectedIntent: "code_execution" },
  { id: 247, category: "code", question: "Génère un UUID", expectedIntent: "code_execution" },
  { id: 248, category: "code", question: "Crée un décorateur Python", expectedIntent: "code_execution" },
  { id: 249, category: "code", question: "Exécute un générateur", expectedIntent: "code_execution" },
  { id: 250, category: "code", question: "Calcule le sinus de 45 degrés", expectedIntent: "code_execution" },

  // MÉTÉO (30)
  { id: 251, category: "weather", question: "Quelle est la météo à Paris ?", expectedIntent: "weather" },
  { id: 252, category: "weather", question: "Quel temps fait-il à Lyon ?", expectedIntent: "weather" },
  { id: 253, category: "weather", question: "Donne-moi la météo de Marseille", expectedIntent: "weather" },
  { id: 254, category: "weather", question: "Il fait combien à Bordeaux ?", expectedIntent: "weather" },
  { id: 255, category: "weather", question: "C'est quoi la température à Nice ?", expectedIntent: "weather" },
  { id: 256, category: "weather", question: "What's the weather in London?", expectedIntent: "weather" },
  { id: 257, category: "weather", question: "How's the weather in New York?", expectedIntent: "weather" },
  { id: 258, category: "weather", question: "Wie ist das Wetter in Berlin?", expectedIntent: "weather" },
  { id: 259, category: "weather", question: "Météo Tokyo", expectedIntent: "weather" },
  { id: 260, category: "weather", question: "Température à Rome", expectedIntent: "weather" },
  { id: 261, category: "weather", question: "Est-ce qu'il pleut à Bruxelles ?", expectedIntent: "weather" },
  { id: 262, category: "weather", question: "Il fait beau à Madrid ?", expectedIntent: "weather" },
  { id: 263, category: "weather", question: "Prévisions météo pour Amsterdam", expectedIntent: "weather" },
  { id: 264, category: "weather", question: "Quel temps à Lisbonne ?", expectedIntent: "weather" },
  { id: 265, category: "weather", question: "Météo actuelle à Vienne", expectedIntent: "weather" },
  { id: 266, category: "weather", question: "Il neige à Moscou ?", expectedIntent: "weather" },
  { id: 267, category: "weather", question: "Température à Dubai", expectedIntent: "weather" },
  { id: 268, category: "weather", question: "Météo Sydney", expectedIntent: "weather" },
  { id: 269, category: "weather", question: "Quel temps à Toronto ?", expectedIntent: "weather" },
  { id: 270, category: "weather", question: "Il fait froid à Stockholm ?", expectedIntent: "weather" },
  { id: 271, category: "weather", question: "Météo à Luxembourg", expectedIntent: "weather" },
  { id: 272, category: "weather", question: "Température à Genève", expectedIntent: "weather" },
  { id: 273, category: "weather", question: "Quel temps fait-il à Zurich ?", expectedIntent: "weather" },
  { id: 274, category: "weather", question: "Météo Monaco", expectedIntent: "weather" },
  { id: 275, category: "weather", question: "Il fait chaud à Miami ?", expectedIntent: "weather" },
  { id: 276, category: "weather", question: "Prévisions pour Los Angeles", expectedIntent: "weather" },
  { id: 277, category: "weather", question: "Météo San Francisco", expectedIntent: "weather" },
  { id: 278, category: "weather", question: "Température à Chicago", expectedIntent: "weather" },
  { id: 279, category: "weather", question: "Quel temps à Seattle ?", expectedIntent: "weather" },
  { id: 280, category: "weather", question: "Météo à Denver", expectedIntent: "weather" },

  // CRYPTO (30)
  { id: 281, category: "crypto", question: "Quel est le prix du Bitcoin ?", expectedIntent: "crypto" },
  { id: 282, category: "crypto", question: "Combien vaut l'Ethereum ?", expectedIntent: "crypto" },
  { id: 283, category: "crypto", question: "Prix du BTC", expectedIntent: "crypto" },
  { id: 284, category: "crypto", question: "Cours de l'ETH", expectedIntent: "crypto" },
  { id: 285, category: "crypto", question: "Bitcoin price", expectedIntent: "crypto" },
  { id: 286, category: "crypto", question: "What's the price of Solana?", expectedIntent: "crypto" },
  { id: 287, category: "crypto", question: "Wie viel kostet Bitcoin?", expectedIntent: "crypto" },
  { id: 288, category: "crypto", question: "Prix du Cardano", expectedIntent: "crypto" },
  { id: 289, category: "crypto", question: "Cours du Dogecoin", expectedIntent: "crypto" },
  { id: 290, category: "crypto", question: "Valeur du XRP", expectedIntent: "crypto" },
  { id: 291, category: "crypto", question: "Prix du Polkadot", expectedIntent: "crypto" },
  { id: 292, category: "crypto", question: "Combien coûte le Litecoin ?", expectedIntent: "crypto" },
  { id: 293, category: "crypto", question: "Cours du Chainlink", expectedIntent: "crypto" },
  { id: 294, category: "crypto", question: "Prix du Avalanche", expectedIntent: "crypto" },
  { id: 295, category: "crypto", question: "Valeur du Polygon", expectedIntent: "crypto" },
  { id: 296, category: "crypto", question: "BTC en euros", expectedIntent: "crypto" },
  { id: 297, category: "crypto", question: "ETH en dollars", expectedIntent: "crypto" },
  { id: 298, category: "crypto", question: "Le Bitcoin monte ou descend ?", expectedIntent: "crypto" },
  { id: 299, category: "crypto", question: "Tendance de l'Ethereum", expectedIntent: "crypto" },
  { id: 300, category: "crypto", question: "Market cap du Bitcoin", expectedIntent: "crypto" },
  { id: 301, category: "crypto", question: "Volume du BTC", expectedIntent: "crypto" },
  { id: 302, category: "crypto", question: "Prix du Shiba Inu", expectedIntent: "crypto" },
  { id: 303, category: "crypto", question: "Cours du Tron", expectedIntent: "crypto" },
  { id: 304, category: "crypto", question: "Valeur du Cosmos", expectedIntent: "crypto" },
  { id: 305, category: "crypto", question: "Prix du Near Protocol", expectedIntent: "crypto" },
  { id: 306, category: "crypto", question: "Combien vaut le Uniswap ?", expectedIntent: "crypto" },
  { id: 307, category: "crypto", question: "Cours du Aave", expectedIntent: "crypto" },
  { id: 308, category: "crypto", question: "Prix du Maker", expectedIntent: "crypto" },
  { id: 309, category: "crypto", question: "Valeur du Compound", expectedIntent: "crypto" },
  { id: 310, category: "crypto", question: "Le Solana aujourd'hui", expectedIntent: "crypto" },

  // RECHERCHE WEB (30)
  { id: 311, category: "search", question: "Cherche des informations sur l'IA", expectedIntent: "web_search" },
  { id: 312, category: "search", question: "Recherche les dernières nouvelles sur Tesla", expectedIntent: "web_search" },
  { id: 313, category: "search", question: "Trouve des articles sur le changement climatique", expectedIntent: "web_search" },
  { id: 314, category: "search", question: "Google les actualités tech", expectedIntent: "web_search" },
  { id: 315, category: "search", question: "Qu'est-ce que le machine learning ?", expectedIntent: "web_search" },
  { id: 316, category: "search", question: "Search for news about Apple", expectedIntent: "web_search" },
  { id: 317, category: "search", question: "Find information about quantum computing", expectedIntent: "web_search" },
  { id: 318, category: "search", question: "Suche nach Nachrichten über Deutschland", expectedIntent: "web_search" },
  { id: 319, category: "search", question: "Qui est Elon Musk ?", expectedIntent: "web_search" },
  { id: 320, category: "search", question: "Dernières nouvelles sur la guerre en Ukraine", expectedIntent: "web_search" },
  { id: 321, category: "search", question: "Actualités sportives du jour", expectedIntent: "web_search" },
  { id: 322, category: "search", question: "Résultats de la Ligue des Champions", expectedIntent: "web_search" },
  { id: 323, category: "search", question: "Cherche les meilleurs restaurants à Paris", expectedIntent: "web_search" },
  { id: 324, category: "search", question: "Trouve des hôtels à Rome", expectedIntent: "web_search" },
  { id: 325, category: "search", question: "Recherche des vols pour New York", expectedIntent: "web_search" },
  { id: 326, category: "search", question: "Qu'est-ce qui s'est passé aujourd'hui ?", expectedIntent: "web_search" },
  { id: 327, category: "search", question: "Nouvelles sur les élections", expectedIntent: "web_search" },
  { id: 328, category: "search", question: "Cherche des tutoriels Python", expectedIntent: "web_search" },
  { id: 329, category: "search", question: "Trouve des cours de JavaScript", expectedIntent: "web_search" },
  { id: 330, category: "search", question: "Recherche des livres sur l'investissement", expectedIntent: "web_search" },
  { id: 331, category: "search", question: "Qui a gagné le match hier ?", expectedIntent: "web_search" },
  { id: 332, category: "search", question: "Dernières sorties Netflix", expectedIntent: "web_search" },
  { id: 333, category: "search", question: "Films à voir en ce moment", expectedIntent: "web_search" },
  { id: 334, category: "search", question: "Cherche des recettes de gâteau", expectedIntent: "web_search" },
  { id: 335, category: "search", question: "Trouve des exercices de fitness", expectedIntent: "web_search" },
  { id: 336, category: "search", question: "Recherche des conseils de productivité", expectedIntent: "web_search" },
  { id: 337, category: "search", question: "Qu'est-ce que la blockchain ?", expectedIntent: "web_search" },
  { id: 338, category: "search", question: "Comment fonctionne ChatGPT ?", expectedIntent: "web_search" },
  { id: 339, category: "search", question: "Cherche des informations sur SpaceX", expectedIntent: "web_search" },
  { id: 340, category: "search", question: "Dernières découvertes scientifiques", expectedIntent: "web_search" },

  // TRANSITIONS (50)
  { id: 341, category: "transition", question: "Non, je ne veux plus d'image, crée-moi un site", expectedIntent: "site_creation" },
  { id: 342, category: "transition", question: "Arrête les images, fais-moi une application", expectedIntent: "app_creation" },
  { id: 343, category: "transition", question: "Stop, je veux du code maintenant", expectedIntent: "code_execution" },
  { id: 344, category: "transition", question: "Pas une image, une vraie application", expectedIntent: "app_creation" },
  { id: 345, category: "transition", question: "Je ne veux pas de site, je veux une app", expectedIntent: "app_creation" },
  { id: 346, category: "transition", question: "Oublie le code, génère une image", expectedIntent: "image_generation" },
  { id: 347, category: "transition", question: "Laisse tomber, donne-moi la météo", expectedIntent: "weather" },
  { id: 348, category: "transition", question: "Non merci, cherche plutôt sur le web", expectedIntent: "web_search" },
  { id: 349, category: "transition", question: "Maintenant je veux le prix du Bitcoin", expectedIntent: "crypto" },
  { id: 350, category: "transition", question: "Changeons de sujet, parlons un peu", expectedIntent: "conversation" },
  { id: 351, category: "transition", question: "Finalement, crée-moi un site web", expectedIntent: "site_creation" },
  { id: 352, category: "transition", question: "En fait, je préfère une application", expectedIntent: "app_creation" },
  { id: 353, category: "transition", question: "Non, exécute du code à la place", expectedIntent: "code_execution" },
  { id: 354, category: "transition", question: "Plutôt une image s'il te plaît", expectedIntent: "image_generation" },
  { id: 355, category: "transition", question: "Je veux la météo maintenant", expectedIntent: "weather" },
  { id: 356, category: "transition", question: "Donne-moi le cours du crypto", expectedIntent: "crypto" },
  { id: 357, category: "transition", question: "Fais une recherche web à la place", expectedIntent: "web_search" },
  { id: 358, category: "transition", question: "Parlons plutôt de toi", expectedIntent: "conversation" },
  { id: 359, category: "transition", question: "Arrête tout, je veux un site", expectedIntent: "site_creation" },
  { id: 360, category: "transition", question: "Stop, crée une app", expectedIntent: "app_creation" },
  { id: 361, category: "transition", question: "Non non, calcule quelque chose", expectedIntent: "code_execution" },
  { id: 362, category: "transition", question: "Génère plutôt une image", expectedIntent: "image_generation" },
  { id: 363, category: "transition", question: "La météo s'il te plaît", expectedIntent: "weather" },
  { id: 364, category: "transition", question: "Le Bitcoin maintenant", expectedIntent: "crypto" },
  { id: 365, category: "transition", question: "Cherche sur Google", expectedIntent: "web_search" },
  { id: 366, category: "transition", question: "Discutons un peu", expectedIntent: "conversation" },
  { id: 367, category: "transition", question: "Je ne veux plus de conversation, crée un site", expectedIntent: "site_creation" },
  { id: 368, category: "transition", question: "Assez parlé, fais une application", expectedIntent: "app_creation" },
  { id: 369, category: "transition", question: "Passons au code", expectedIntent: "code_execution" },
  { id: 370, category: "transition", question: "Une image maintenant", expectedIntent: "image_generation" },
  { id: 371, category: "transition", question: "Météo Paris", expectedIntent: "weather" },
  { id: 372, category: "transition", question: "Prix ETH", expectedIntent: "crypto" },
  { id: 373, category: "transition", question: "Recherche IA", expectedIntent: "web_search" },
  { id: 374, category: "transition", question: "Salut, ça va ?", expectedIntent: "conversation" },
  { id: 375, category: "transition", question: "Crée un portfolio", expectedIntent: "site_creation" },
  { id: 376, category: "transition", question: "Fais un chatbot", expectedIntent: "app_creation" },
  { id: 377, category: "transition", question: "Calcule 100!", expectedIntent: "code_execution" },
  { id: 378, category: "transition", question: "Dessine un dragon", expectedIntent: "image_generation" },
  { id: 379, category: "transition", question: "Température Lyon", expectedIntent: "weather" },
  { id: 380, category: "transition", question: "Solana prix", expectedIntent: "crypto" },
  { id: 381, category: "transition", question: "News tech", expectedIntent: "web_search" },
  { id: 382, category: "transition", question: "Merci beaucoup", expectedIntent: "conversation" },
  { id: 383, category: "transition", question: "Landing page startup", expectedIntent: "site_creation" },
  { id: 384, category: "transition", question: "Assistant IA", expectedIntent: "app_creation" },
  { id: 385, category: "transition", question: "Fibonacci 20", expectedIntent: "code_execution" },
  { id: 386, category: "transition", question: "Logo entreprise", expectedIntent: "image_generation" },
  { id: 387, category: "transition", question: "Météo demain", expectedIntent: "weather" },
  { id: 388, category: "transition", question: "BTC USD", expectedIntent: "crypto" },
  { id: 389, category: "transition", question: "Actualités France", expectedIntent: "web_search" },
  { id: 390, category: "transition", question: "Tu es génial", expectedIntent: "conversation" },

  // NÉGATIONS (30)
  { id: 391, category: "negation", question: "Non, pas ça", expectedIntent: "conversation" },
  { id: 392, category: "negation", question: "Je ne veux pas d'image", expectedIntent: "conversation" },
  { id: 393, category: "negation", question: "Arrête", expectedIntent: "conversation" },
  { id: 394, category: "negation", question: "Stop", expectedIntent: "conversation" },
  { id: 395, category: "negation", question: "Annule", expectedIntent: "conversation" },
  { id: 396, category: "negation", question: "Oublie ce que j'ai dit", expectedIntent: "conversation" },
  { id: 397, category: "negation", question: "Laisse tomber", expectedIntent: "conversation" },
  { id: 398, category: "negation", question: "Pas maintenant", expectedIntent: "conversation" },
  { id: 399, category: "negation", question: "Plus tard", expectedIntent: "conversation" },
  { id: 400, category: "negation", question: "Non merci", expectedIntent: "conversation" },
  { id: 401, category: "negation", question: "Je ne veux rien", expectedIntent: "conversation" },
  { id: 402, category: "negation", question: "Rien du tout", expectedIntent: "conversation" },
  { id: 403, category: "negation", question: "Pas besoin", expectedIntent: "conversation" },
  { id: 404, category: "negation", question: "C'est bon", expectedIntent: "conversation" },
  { id: 405, category: "negation", question: "Ça suffit", expectedIntent: "conversation" },
  { id: 406, category: "negation", question: "J'ai changé d'avis", expectedIntent: "conversation" },
  { id: 407, category: "negation", question: "Finalement non", expectedIntent: "conversation" },
  { id: 408, category: "negation", question: "Pas la peine", expectedIntent: "conversation" },
  { id: 409, category: "negation", question: "Inutile", expectedIntent: "conversation" },
  { id: 410, category: "negation", question: "Oublie", expectedIntent: "conversation" },
  { id: 411, category: "negation", question: "Cancel", expectedIntent: "conversation" },
  { id: 412, category: "negation", question: "Nevermind", expectedIntent: "conversation" },
  { id: 413, category: "negation", question: "Forget it", expectedIntent: "conversation" },
  { id: 414, category: "negation", question: "No thanks", expectedIntent: "conversation" },
  { id: 415, category: "negation", question: "Not now", expectedIntent: "conversation" },
  { id: 416, category: "negation", question: "Nein danke", expectedIntent: "conversation" },
  { id: 417, category: "negation", question: "Je refuse", expectedIntent: "conversation" },
  { id: 418, category: "negation", question: "Non non non", expectedIntent: "conversation" },
  { id: 419, category: "negation", question: "Absolument pas", expectedIntent: "conversation" },
  { id: 420, category: "negation", question: "Jamais", expectedIntent: "conversation" },
];

export { TEST_QUESTIONS, TestCase, TestResult };
