/**
 * Stress Test pour Phoenix AI
 * 500+ questions pour tester la compréhension et les transitions
 */

export interface TestQuestion {
  id: number;
  category: string;
  question: string;
  expectedIntent: string;
  previousContext?: string; // Pour les tests de transition
  shouldTriggerTransition?: boolean;
  shouldTriggerNegation?: boolean;
}

// ==========================================
// CATÉGORIE 1: CONVERSATION SIMPLE (50)
// ==========================================
const conversationQuestions: TestQuestion[] = [
  { id: 1, category: 'conversation', question: 'Bonjour', expectedIntent: 'conversation' },
  { id: 2, category: 'conversation', question: 'Salut Phoenix', expectedIntent: 'conversation' },
  { id: 3, category: 'conversation', question: 'Comment ça va?', expectedIntent: 'conversation' },
  { id: 4, category: 'conversation', question: 'Hello', expectedIntent: 'conversation' },
  { id: 5, category: 'conversation', question: 'Hi there', expectedIntent: 'conversation' },
  { id: 6, category: 'conversation', question: 'Good morning', expectedIntent: 'conversation' },
  { id: 7, category: 'conversation', question: 'Bonsoir', expectedIntent: 'conversation' },
  { id: 8, category: 'conversation', question: 'Merci beaucoup', expectedIntent: 'conversation' },
  { id: 9, category: 'conversation', question: 'Thanks', expectedIntent: 'conversation' },
  { id: 10, category: 'conversation', question: 'Au revoir', expectedIntent: 'conversation' },
  { id: 11, category: 'conversation', question: 'Bye', expectedIntent: 'conversation' },
  { id: 12, category: 'conversation', question: 'À bientôt', expectedIntent: 'conversation' },
  { id: 13, category: 'conversation', question: 'Comment tu t\'appelles?', expectedIntent: 'conversation' },
  { id: 14, category: 'conversation', question: 'Qui es-tu?', expectedIntent: 'conversation' },
  { id: 15, category: 'conversation', question: 'What can you do?', expectedIntent: 'conversation' },
  { id: 16, category: 'conversation', question: 'Que sais-tu faire?', expectedIntent: 'conversation' },
  { id: 17, category: 'conversation', question: 'Aide-moi', expectedIntent: 'conversation' },
  { id: 18, category: 'conversation', question: 'J\'ai besoin d\'aide', expectedIntent: 'conversation' },
  { id: 19, category: 'conversation', question: 'Help me', expectedIntent: 'conversation' },
  { id: 20, category: 'conversation', question: 'C\'est quoi Phoenix?', expectedIntent: 'conversation' },
  { id: 21, category: 'conversation', question: 'Tu es intelligent?', expectedIntent: 'conversation' },
  { id: 22, category: 'conversation', question: 'Are you an AI?', expectedIntent: 'conversation' },
  { id: 23, category: 'conversation', question: 'Tu parles français?', expectedIntent: 'conversation' },
  { id: 24, category: 'conversation', question: 'Do you speak English?', expectedIntent: 'conversation' },
  { id: 25, category: 'conversation', question: 'Quelle heure est-il?', expectedIntent: 'conversation' },
  { id: 26, category: 'conversation', question: 'What time is it?', expectedIntent: 'conversation' },
  { id: 27, category: 'conversation', question: 'Quel jour sommes-nous?', expectedIntent: 'conversation' },
  { id: 28, category: 'conversation', question: 'What day is today?', expectedIntent: 'conversation' },
  { id: 29, category: 'conversation', question: 'Je m\'ennuie', expectedIntent: 'conversation' },
  { id: 30, category: 'conversation', question: 'Raconte-moi une blague', expectedIntent: 'conversation' },
  { id: 31, category: 'conversation', question: 'Tell me a joke', expectedIntent: 'conversation' },
  { id: 32, category: 'conversation', question: 'Tu es drôle', expectedIntent: 'conversation' },
  { id: 33, category: 'conversation', question: 'Parfait', expectedIntent: 'conversation' },
  { id: 34, category: 'conversation', question: 'Super', expectedIntent: 'conversation' },
  { id: 35, category: 'conversation', question: 'Excellent', expectedIntent: 'conversation' },
  { id: 36, category: 'conversation', question: 'D\'accord', expectedIntent: 'conversation' },
  { id: 37, category: 'conversation', question: 'OK', expectedIntent: 'conversation' },
  { id: 38, category: 'conversation', question: 'Compris', expectedIntent: 'conversation' },
  { id: 39, category: 'conversation', question: 'Je comprends', expectedIntent: 'conversation' },
  { id: 40, category: 'conversation', question: 'C\'est bien', expectedIntent: 'conversation' },
  { id: 41, category: 'conversation', question: 'That\'s great', expectedIntent: 'conversation' },
  { id: 42, category: 'conversation', question: 'Awesome', expectedIntent: 'conversation' },
  { id: 43, category: 'conversation', question: 'Cool', expectedIntent: 'conversation' },
  { id: 44, category: 'conversation', question: 'Nice', expectedIntent: 'conversation' },
  { id: 45, category: 'conversation', question: 'Bien joué', expectedIntent: 'conversation' },
  { id: 46, category: 'conversation', question: 'Bravo', expectedIntent: 'conversation' },
  { id: 47, category: 'conversation', question: 'Félicitations', expectedIntent: 'conversation' },
  { id: 48, category: 'conversation', question: 'Je suis content', expectedIntent: 'conversation' },
  { id: 49, category: 'conversation', question: 'I\'m happy', expectedIntent: 'conversation' },
  { id: 50, category: 'conversation', question: 'Ça me plaît', expectedIntent: 'conversation' },
];

// ==========================================
// CATÉGORIE 2: GÉNÉRATION D'IMAGES (50)
// ==========================================
const imageQuestions: TestQuestion[] = [
  { id: 51, category: 'image', question: 'Génère une image de chat', expectedIntent: 'image_generation' },
  { id: 52, category: 'image', question: 'Crée-moi une image de paysage', expectedIntent: 'image_generation' },
  { id: 53, category: 'image', question: 'Fais une photo de montagne', expectedIntent: 'image_generation' },
  { id: 54, category: 'image', question: 'Generate an image of a sunset', expectedIntent: 'image_generation' },
  { id: 55, category: 'image', question: 'Create a picture of a dog', expectedIntent: 'image_generation' },
  { id: 56, category: 'image', question: 'Génère une image de voiture de sport rouge', expectedIntent: 'image_generation' },
  { id: 57, category: 'image', question: 'Crée une illustration de robot futuriste', expectedIntent: 'image_generation' },
  { id: 58, category: 'image', question: 'Fais-moi une image de plage tropicale', expectedIntent: 'image_generation' },
  { id: 59, category: 'image', question: 'Generate a fantasy castle', expectedIntent: 'image_generation' },
  { id: 60, category: 'image', question: 'Create an image of a dragon', expectedIntent: 'image_generation' },
  { id: 61, category: 'image', question: 'Génère une image de forêt enchantée', expectedIntent: 'image_generation' },
  { id: 62, category: 'image', question: 'Crée une image de ville futuriste', expectedIntent: 'image_generation' },
  { id: 63, category: 'image', question: 'Fais une image de pizza', expectedIntent: 'image_generation' },
  { id: 64, category: 'image', question: 'Generate a portrait of a woman', expectedIntent: 'image_generation' },
  { id: 65, category: 'image', question: 'Create an abstract art piece', expectedIntent: 'image_generation' },
  { id: 66, category: 'image', question: 'Génère une image de lion majestueux', expectedIntent: 'image_generation' },
  { id: 67, category: 'image', question: 'Crée une image d\'astronaute sur Mars', expectedIntent: 'image_generation' },
  { id: 68, category: 'image', question: 'Fais une image de jardin japonais', expectedIntent: 'image_generation' },
  { id: 69, category: 'image', question: 'Generate a cyberpunk scene', expectedIntent: 'image_generation' },
  { id: 70, category: 'image', question: 'Create an image of a waterfall', expectedIntent: 'image_generation' },
  { id: 71, category: 'image', question: 'Génère une image de café parisien', expectedIntent: 'image_generation' },
  { id: 72, category: 'image', question: 'Crée une image de bateau sur l\'océan', expectedIntent: 'image_generation' },
  { id: 73, category: 'image', question: 'Fais une image de château médiéval', expectedIntent: 'image_generation' },
  { id: 74, category: 'image', question: 'Generate a snowy mountain landscape', expectedIntent: 'image_generation' },
  { id: 75, category: 'image', question: 'Create an image of a rainbow', expectedIntent: 'image_generation' },
  { id: 76, category: 'image', question: 'Génère une image de fleurs colorées', expectedIntent: 'image_generation' },
  { id: 77, category: 'image', question: 'Crée une image de papillon', expectedIntent: 'image_generation' },
  { id: 78, category: 'image', question: 'Fais une image de lune', expectedIntent: 'image_generation' },
  { id: 79, category: 'image', question: 'Generate a space station', expectedIntent: 'image_generation' },
  { id: 80, category: 'image', question: 'Create an image of a phoenix bird', expectedIntent: 'image_generation' },
  { id: 81, category: 'image', question: 'Génère une image de beau gosse turc devant un hôtel', expectedIntent: 'image_generation' },
  { id: 82, category: 'image', question: 'Crée une image de femme élégante', expectedIntent: 'image_generation' },
  { id: 83, category: 'image', question: 'Fais une image de famille heureuse', expectedIntent: 'image_generation' },
  { id: 84, category: 'image', question: 'Generate a luxury car', expectedIntent: 'image_generation' },
  { id: 85, category: 'image', question: 'Create an image of a modern house', expectedIntent: 'image_generation' },
  { id: 86, category: 'image', question: 'Génère une image de restaurant chic', expectedIntent: 'image_generation' },
  { id: 87, category: 'image', question: 'Crée une image de bureau moderne', expectedIntent: 'image_generation' },
  { id: 88, category: 'image', question: 'Fais une image de salle de sport', expectedIntent: 'image_generation' },
  { id: 89, category: 'image', question: 'Generate a tropical beach resort', expectedIntent: 'image_generation' },
  { id: 90, category: 'image', question: 'Create an image of a cozy living room', expectedIntent: 'image_generation' },
  { id: 91, category: 'image', question: 'Génère une image de cuisine moderne', expectedIntent: 'image_generation' },
  { id: 92, category: 'image', question: 'Crée une image de chambre luxueuse', expectedIntent: 'image_generation' },
  { id: 93, category: 'image', question: 'Fais une image de piscine', expectedIntent: 'image_generation' },
  { id: 94, category: 'image', question: 'Generate a garden with flowers', expectedIntent: 'image_generation' },
  { id: 95, category: 'image', question: 'Create an image of a bookshelf', expectedIntent: 'image_generation' },
  { id: 96, category: 'image', question: 'Génère une image de coucher de soleil sur la mer', expectedIntent: 'image_generation' },
  { id: 97, category: 'image', question: 'Crée une image de lever de soleil', expectedIntent: 'image_generation' },
  { id: 98, category: 'image', question: 'Fais une image de nuit étoilée', expectedIntent: 'image_generation' },
  { id: 99, category: 'image', question: 'Generate northern lights', expectedIntent: 'image_generation' },
  { id: 100, category: 'image', question: 'Create an image of a thunderstorm', expectedIntent: 'image_generation' },
];

// ==========================================
// CATÉGORIE 3: CRÉATION DE SITES WEB (50)
// ==========================================
const siteQuestions: TestQuestion[] = [
  { id: 101, category: 'site', question: 'Crée-moi un site web', expectedIntent: 'site_creation' },
  { id: 102, category: 'site', question: 'Fais-moi un site pour mon restaurant', expectedIntent: 'site_creation' },
  { id: 103, category: 'site', question: 'Create a website for my business', expectedIntent: 'site_creation' },
  { id: 104, category: 'site', question: 'Build me a landing page', expectedIntent: 'site_creation' },
  { id: 105, category: 'site', question: 'Crée une page web pour mon hôtel', expectedIntent: 'site_creation' },
  { id: 106, category: 'site', question: 'Fais-moi un site e-commerce', expectedIntent: 'site_creation' },
  { id: 107, category: 'site', question: 'Create an online store', expectedIntent: 'site_creation' },
  { id: 108, category: 'site', question: 'Build a portfolio website', expectedIntent: 'site_creation' },
  { id: 109, category: 'site', question: 'Crée un site vitrine', expectedIntent: 'site_creation' },
  { id: 110, category: 'site', question: 'Fais-moi un blog', expectedIntent: 'site_creation' },
  { id: 111, category: 'site', question: 'Create a blog website', expectedIntent: 'site_creation' },
  { id: 112, category: 'site', question: 'Build me a company website', expectedIntent: 'site_creation' },
  { id: 113, category: 'site', question: 'Crée un site pour ma startup', expectedIntent: 'site_creation' },
  { id: 114, category: 'site', question: 'Fais-moi un site de réservation', expectedIntent: 'site_creation' },
  { id: 115, category: 'site', question: 'Create a booking website', expectedIntent: 'site_creation' },
  { id: 116, category: 'site', question: 'Build a restaurant website', expectedIntent: 'site_creation' },
  { id: 117, category: 'site', question: 'Crée un site pour mon salon de coiffure', expectedIntent: 'site_creation' },
  { id: 118, category: 'site', question: 'Fais-moi un site pour mon cabinet médical', expectedIntent: 'site_creation' },
  { id: 119, category: 'site', question: 'Create a dental clinic website', expectedIntent: 'site_creation' },
  { id: 120, category: 'site', question: 'Build a gym website', expectedIntent: 'site_creation' },
  { id: 121, category: 'site', question: 'Crée un site pour mon école', expectedIntent: 'site_creation' },
  { id: 122, category: 'site', question: 'Fais-moi un site pour mon association', expectedIntent: 'site_creation' },
  { id: 123, category: 'site', question: 'Create a nonprofit website', expectedIntent: 'site_creation' },
  { id: 124, category: 'site', question: 'Build a church website', expectedIntent: 'site_creation' },
  { id: 125, category: 'site', question: 'Crée un site pour mon agence immobilière', expectedIntent: 'site_creation' },
  { id: 126, category: 'site', question: 'Fais-moi un site pour mon cabinet d\'avocats', expectedIntent: 'site_creation' },
  { id: 127, category: 'site', question: 'Create a law firm website', expectedIntent: 'site_creation' },
  { id: 128, category: 'site', question: 'Build an accounting firm website', expectedIntent: 'site_creation' },
  { id: 129, category: 'site', question: 'Crée un site pour mon garage', expectedIntent: 'site_creation' },
  { id: 130, category: 'site', question: 'Fais-moi un site pour mon food truck', expectedIntent: 'site_creation' },
  { id: 131, category: 'site', question: 'Create a food delivery website', expectedIntent: 'site_creation' },
  { id: 132, category: 'site', question: 'Build a catering website', expectedIntent: 'site_creation' },
  { id: 133, category: 'site', question: 'Crée un site pour mon mariage', expectedIntent: 'site_creation' },
  { id: 134, category: 'site', question: 'Fais-moi un site pour mon événement', expectedIntent: 'site_creation' },
  { id: 135, category: 'site', question: 'Create an event website', expectedIntent: 'site_creation' },
  { id: 136, category: 'site', question: 'Build a conference website', expectedIntent: 'site_creation' },
  { id: 137, category: 'site', question: 'Crée un site pour mon podcast', expectedIntent: 'site_creation' },
  { id: 138, category: 'site', question: 'Fais-moi un site pour ma chaîne YouTube', expectedIntent: 'site_creation' },
  { id: 139, category: 'site', question: 'Create a musician website', expectedIntent: 'site_creation' },
  { id: 140, category: 'site', question: 'Build an artist portfolio', expectedIntent: 'site_creation' },
  { id: 141, category: 'site', question: 'Crée un site pour mon photographe', expectedIntent: 'site_creation' },
  { id: 142, category: 'site', question: 'Fais-moi un site pour mon studio de design', expectedIntent: 'site_creation' },
  { id: 143, category: 'site', question: 'Create a freelancer website', expectedIntent: 'site_creation' },
  { id: 144, category: 'site', question: 'Build a consultant website', expectedIntent: 'site_creation' },
  { id: 145, category: 'site', question: 'Crée un site pour mon coach sportif', expectedIntent: 'site_creation' },
  { id: 146, category: 'site', question: 'Fais-moi un site pour mon nutritionniste', expectedIntent: 'site_creation' },
  { id: 147, category: 'site', question: 'Create a fitness trainer website', expectedIntent: 'site_creation' },
  { id: 148, category: 'site', question: 'Build a yoga studio website', expectedIntent: 'site_creation' },
  { id: 149, category: 'site', question: 'Crée un site pour mon spa', expectedIntent: 'site_creation' },
  { id: 150, category: 'site', question: 'Fais-moi un site pour mon centre de bien-être', expectedIntent: 'site_creation' },
];

// ==========================================
// CATÉGORIE 4: CRÉATION D'APPLICATIONS (50)
// ==========================================
const appQuestions: TestQuestion[] = [
  { id: 151, category: 'app', question: 'Crée-moi une application de chatbot', expectedIntent: 'app_creation' },
  { id: 152, category: 'app', question: 'Fais-moi un agent IA', expectedIntent: 'app_creation' },
  { id: 153, category: 'app', question: 'Create a chatbot application', expectedIntent: 'app_creation' },
  { id: 154, category: 'app', question: 'Build me an AI agent', expectedIntent: 'app_creation' },
  { id: 155, category: 'app', question: 'Crée une vraie application de chat', expectedIntent: 'app_creation' },
  { id: 156, category: 'app', question: 'Fais-moi un bot de conversation', expectedIntent: 'app_creation' },
  { id: 157, category: 'app', question: 'Create a conversational bot', expectedIntent: 'app_creation' },
  { id: 158, category: 'app', question: 'Build an assistant virtuel', expectedIntent: 'app_creation' },
  { id: 159, category: 'app', question: 'Crée une application fonctionnelle', expectedIntent: 'app_creation' },
  { id: 160, category: 'app', question: 'Fais-moi une app qui marche', expectedIntent: 'app_creation' },
  { id: 161, category: 'app', question: 'Create a working application', expectedIntent: 'app_creation' },
  { id: 162, category: 'app', question: 'Build a functional chatbot', expectedIntent: 'app_creation' },
  { id: 163, category: 'app', question: 'Crée un chatbot intelligent', expectedIntent: 'app_creation' },
  { id: 164, category: 'app', question: 'Fais-moi un assistant personnel', expectedIntent: 'app_creation' },
  { id: 165, category: 'app', question: 'Create a personal assistant', expectedIntent: 'app_creation' },
  { id: 166, category: 'app', question: 'Build a customer service bot', expectedIntent: 'app_creation' },
  { id: 167, category: 'app', question: 'Crée un bot de support client', expectedIntent: 'app_creation' },
  { id: 168, category: 'app', question: 'Fais-moi un chatbot FAQ', expectedIntent: 'app_creation' },
  { id: 169, category: 'app', question: 'Create a FAQ bot', expectedIntent: 'app_creation' },
  { id: 170, category: 'app', question: 'Build a help desk bot', expectedIntent: 'app_creation' },
  { id: 171, category: 'app', question: 'Crée une application de réservation', expectedIntent: 'app_creation' },
  { id: 172, category: 'app', question: 'Fais-moi une app de commande', expectedIntent: 'app_creation' },
  { id: 173, category: 'app', question: 'Create a booking app', expectedIntent: 'app_creation' },
  { id: 174, category: 'app', question: 'Build an ordering system', expectedIntent: 'app_creation' },
  { id: 175, category: 'app', question: 'Crée une application de gestion', expectedIntent: 'app_creation' },
  { id: 176, category: 'app', question: 'Fais-moi un dashboard', expectedIntent: 'app_creation' },
  { id: 177, category: 'app', question: 'Create a management dashboard', expectedIntent: 'app_creation' },
  { id: 178, category: 'app', question: 'Build an admin panel', expectedIntent: 'app_creation' },
  { id: 179, category: 'app', question: 'Crée une application de suivi', expectedIntent: 'app_creation' },
  { id: 180, category: 'app', question: 'Fais-moi un tracker', expectedIntent: 'app_creation' },
  { id: 181, category: 'app', question: 'Create a tracking app', expectedIntent: 'app_creation' },
  { id: 182, category: 'app', question: 'Build a monitoring system', expectedIntent: 'app_creation' },
  { id: 183, category: 'app', question: 'Crée une application de notes', expectedIntent: 'app_creation' },
  { id: 184, category: 'app', question: 'Fais-moi une app todo list', expectedIntent: 'app_creation' },
  { id: 185, category: 'app', question: 'Create a note-taking app', expectedIntent: 'app_creation' },
  { id: 186, category: 'app', question: 'Build a task manager', expectedIntent: 'app_creation' },
  { id: 187, category: 'app', question: 'Crée une application de calendrier', expectedIntent: 'app_creation' },
  { id: 188, category: 'app', question: 'Fais-moi un planificateur', expectedIntent: 'app_creation' },
  { id: 189, category: 'app', question: 'Create a calendar app', expectedIntent: 'app_creation' },
  { id: 190, category: 'app', question: 'Build a scheduler', expectedIntent: 'app_creation' },
  { id: 191, category: 'app', question: 'Crée une application de quiz', expectedIntent: 'app_creation' },
  { id: 192, category: 'app', question: 'Fais-moi un jeu de questions', expectedIntent: 'app_creation' },
  { id: 193, category: 'app', question: 'Create a quiz app', expectedIntent: 'app_creation' },
  { id: 194, category: 'app', question: 'Build a trivia game', expectedIntent: 'app_creation' },
  { id: 195, category: 'app', question: 'Crée une application de sondage', expectedIntent: 'app_creation' },
  { id: 196, category: 'app', question: 'Fais-moi un formulaire de feedback', expectedIntent: 'app_creation' },
  { id: 197, category: 'app', question: 'Create a survey app', expectedIntent: 'app_creation' },
  { id: 198, category: 'app', question: 'Build a feedback form', expectedIntent: 'app_creation' },
  { id: 199, category: 'app', question: 'Crée une application de vote', expectedIntent: 'app_creation' },
  { id: 200, category: 'app', question: 'Fais-moi un système de vote', expectedIntent: 'app_creation' },
];

// ==========================================
// CATÉGORIE 5: EXÉCUTION DE CODE (50)
// ==========================================
const codeQuestions: TestQuestion[] = [
  { id: 201, category: 'code', question: 'Exécute ce code Python', expectedIntent: 'code_execution' },
  { id: 202, category: 'code', question: 'Lance ce script', expectedIntent: 'code_execution' },
  { id: 203, category: 'code', question: 'Run this code', expectedIntent: 'code_execution' },
  { id: 204, category: 'code', question: 'Execute this script', expectedIntent: 'code_execution' },
  { id: 205, category: 'code', question: 'Fais tourner ce programme', expectedIntent: 'code_execution' },
  { id: 206, category: 'code', question: 'Teste ce code', expectedIntent: 'code_execution' },
  { id: 207, category: 'code', question: 'Test this code', expectedIntent: 'code_execution' },
  { id: 208, category: 'code', question: 'Debug this script', expectedIntent: 'code_execution' },
  { id: 209, category: 'code', question: 'Calcule 2 + 2', expectedIntent: 'calculation' },
  { id: 210, category: 'code', question: 'Calculate 10 * 5', expectedIntent: 'calculation' },
  { id: 211, category: 'code', question: 'Combien fait 100 / 4?', expectedIntent: 'calculation' },
  { id: 212, category: 'code', question: 'What is 15 + 27?', expectedIntent: 'calculation' },
  { id: 213, category: 'code', question: 'Exécute print("Hello World")', expectedIntent: 'code_execution' },
  { id: 214, category: 'code', question: 'Run console.log("Test")', expectedIntent: 'code_execution' },
  { id: 215, category: 'code', question: 'Fais un for loop de 1 à 10', expectedIntent: 'code_execution' },
  { id: 216, category: 'code', question: 'Create a function that adds two numbers', expectedIntent: 'code_execution' },
  { id: 217, category: 'code', question: 'Écris et exécute un tri à bulles', expectedIntent: 'code_execution' },
  { id: 218, category: 'code', question: 'Write and run a bubble sort', expectedIntent: 'code_execution' },
  { id: 219, category: 'code', question: 'Exécute un algorithme de Fibonacci', expectedIntent: 'code_execution' },
  { id: 220, category: 'code', question: 'Run a Fibonacci algorithm', expectedIntent: 'code_execution' },
  { id: 221, category: 'code', question: 'Calcule la factorielle de 10', expectedIntent: 'code_execution' },
  { id: 222, category: 'code', question: 'Calculate factorial of 5', expectedIntent: 'code_execution' },
  { id: 223, category: 'code', question: 'Génère des nombres aléatoires', expectedIntent: 'code_execution' },
  { id: 224, category: 'code', question: 'Generate random numbers', expectedIntent: 'code_execution' },
  { id: 225, category: 'code', question: 'Trie cette liste: [5, 2, 8, 1, 9]', expectedIntent: 'code_execution' },
  { id: 226, category: 'code', question: 'Sort this array: [3, 1, 4, 1, 5]', expectedIntent: 'code_execution' },
  { id: 227, category: 'code', question: 'Inverse cette chaîne: "hello"', expectedIntent: 'code_execution' },
  { id: 228, category: 'code', question: 'Reverse this string: "world"', expectedIntent: 'code_execution' },
  { id: 229, category: 'code', question: 'Compte les voyelles dans "bonjour"', expectedIntent: 'code_execution' },
  { id: 230, category: 'code', question: 'Count vowels in "hello world"', expectedIntent: 'code_execution' },
  { id: 231, category: 'code', question: 'Vérifie si "radar" est un palindrome', expectedIntent: 'code_execution' },
  { id: 232, category: 'code', question: 'Check if "level" is a palindrome', expectedIntent: 'code_execution' },
  { id: 233, category: 'code', question: 'Calcule la moyenne de [10, 20, 30]', expectedIntent: 'code_execution' },
  { id: 234, category: 'code', question: 'Calculate average of [5, 10, 15, 20]', expectedIntent: 'code_execution' },
  { id: 235, category: 'code', question: 'Trouve le maximum dans [4, 7, 2, 9, 1]', expectedIntent: 'code_execution' },
  { id: 236, category: 'code', question: 'Find minimum in [8, 3, 6, 1, 5]', expectedIntent: 'code_execution' },
  { id: 237, category: 'code', question: 'Convertis 100 Celsius en Fahrenheit', expectedIntent: 'code_execution' },
  { id: 238, category: 'code', question: 'Convert 32 Fahrenheit to Celsius', expectedIntent: 'code_execution' },
  { id: 239, category: 'code', question: 'Calcule l\'aire d\'un cercle de rayon 5', expectedIntent: 'code_execution' },
  { id: 240, category: 'code', question: 'Calculate area of circle with radius 10', expectedIntent: 'code_execution' },
  { id: 241, category: 'code', question: 'Génère un mot de passe aléatoire', expectedIntent: 'code_execution' },
  { id: 242, category: 'code', question: 'Generate a random password', expectedIntent: 'code_execution' },
  { id: 243, category: 'code', question: 'Crée un UUID', expectedIntent: 'code_execution' },
  { id: 244, category: 'code', question: 'Create a unique ID', expectedIntent: 'code_execution' },
  { id: 245, category: 'code', question: 'Parse ce JSON: {"name": "test"}', expectedIntent: 'code_execution' },
  { id: 246, category: 'code', question: 'Stringify this object: {a: 1, b: 2}', expectedIntent: 'code_execution' },
  { id: 247, category: 'code', question: 'Encode en base64: "hello"', expectedIntent: 'code_execution' },
  { id: 248, category: 'code', question: 'Decode base64: "aGVsbG8="', expectedIntent: 'code_execution' },
  { id: 249, category: 'code', question: 'Hash MD5 de "password"', expectedIntent: 'code_execution' },
  { id: 250, category: 'code', question: 'SHA256 hash of "secret"', expectedIntent: 'code_execution' },
];

// ==========================================
// CATÉGORIE 6: MÉTÉO (30)
// ==========================================
const weatherQuestions: TestQuestion[] = [
  { id: 251, category: 'weather', question: 'Quelle est la météo à Paris?', expectedIntent: 'weather' },
  { id: 252, category: 'weather', question: 'Il fait quel temps à Lyon?', expectedIntent: 'weather' },
  { id: 253, category: 'weather', question: 'Température à Luxembourg', expectedIntent: 'weather' },
  { id: 254, category: 'weather', question: 'What\'s the weather in London?', expectedIntent: 'weather' },
  { id: 255, category: 'weather', question: 'Weather forecast for Berlin', expectedIntent: 'weather' },
  { id: 256, category: 'weather', question: 'Météo du jour', expectedIntent: 'weather' },
  { id: 257, category: 'weather', question: 'Prévisions météo pour demain', expectedIntent: 'weather' },
  { id: 258, category: 'weather', question: 'Fait-il beau à Nice?', expectedIntent: 'weather' },
  { id: 259, category: 'weather', question: 'Quel temps fait-il?', expectedIntent: 'weather' },
  { id: 260, category: 'weather', question: 'Donne-moi la météo', expectedIntent: 'weather' },
  { id: 261, category: 'weather', question: 'Température exacte à Luxembourg', expectedIntent: 'weather' },
  { id: 262, category: 'weather', question: 'Current temperature in New York', expectedIntent: 'weather' },
  { id: 263, category: 'weather', question: 'Va-t-il pleuvoir aujourd\'hui?', expectedIntent: 'weather' },
  { id: 264, category: 'weather', question: 'Will it rain tomorrow?', expectedIntent: 'weather' },
  { id: 265, category: 'weather', question: 'Météo de la semaine', expectedIntent: 'weather' },
  { id: 266, category: 'weather', question: 'Weekly forecast', expectedIntent: 'weather' },
  { id: 267, category: 'weather', question: 'Humidité à Bruxelles', expectedIntent: 'weather' },
  { id: 268, category: 'weather', question: 'Wind speed in Amsterdam', expectedIntent: 'weather' },
  { id: 269, category: 'weather', question: 'UV index à Marseille', expectedIntent: 'weather' },
  { id: 270, category: 'weather', question: 'Air quality in Beijing', expectedIntent: 'weather' },
  { id: 271, category: 'weather', question: 'Température ressentie à Strasbourg', expectedIntent: 'weather' },
  { id: 272, category: 'weather', question: 'Feels like temperature in Chicago', expectedIntent: 'weather' },
  { id: 273, category: 'weather', question: 'Lever du soleil à Tokyo', expectedIntent: 'weather' },
  { id: 274, category: 'weather', question: 'Sunset time in Sydney', expectedIntent: 'weather' },
  { id: 275, category: 'weather', question: 'Neige à Chamonix?', expectedIntent: 'weather' },
  { id: 276, category: 'weather', question: 'Snow forecast for Alps', expectedIntent: 'weather' },
  { id: 277, category: 'weather', question: 'Canicule prévue?', expectedIntent: 'weather' },
  { id: 278, category: 'weather', question: 'Heat wave warning?', expectedIntent: 'weather' },
  { id: 279, category: 'weather', question: 'Météo pour mon voyage à Rome', expectedIntent: 'weather' },
  { id: 280, category: 'weather', question: 'Weather for my trip to Barcelona', expectedIntent: 'weather' },
];

// ==========================================
// CATÉGORIE 7: CRYPTO (30)
// ==========================================
const cryptoQuestions: TestQuestion[] = [
  { id: 281, category: 'crypto', question: 'Prix du Bitcoin', expectedIntent: 'crypto' },
  { id: 282, category: 'crypto', question: 'Cours de l\'Ethereum', expectedIntent: 'crypto' },
  { id: 283, category: 'crypto', question: 'Combien vaut le BTC?', expectedIntent: 'crypto' },
  { id: 284, category: 'crypto', question: 'Bitcoin price', expectedIntent: 'crypto' },
  { id: 285, category: 'crypto', question: 'ETH value', expectedIntent: 'crypto' },
  { id: 286, category: 'crypto', question: 'Crypto prices', expectedIntent: 'crypto' },
  { id: 287, category: 'crypto', question: 'Quel est le prix du Solana?', expectedIntent: 'crypto' },
  { id: 288, category: 'crypto', question: 'Valeur actuelle du Bitcoin', expectedIntent: 'crypto' },
  { id: 289, category: 'crypto', question: 'Cours des cryptomonnaies', expectedIntent: 'crypto' },
  { id: 290, category: 'crypto', question: 'XRP price today', expectedIntent: 'crypto' },
  { id: 291, category: 'crypto', question: 'Cardano ADA value', expectedIntent: 'crypto' },
  { id: 292, category: 'crypto', question: 'Prix du Litecoin', expectedIntent: 'crypto' },
  { id: 293, category: 'crypto', question: 'Polkadot DOT price', expectedIntent: 'crypto' },
  { id: 294, category: 'crypto', question: 'Avalanche AVAX cours', expectedIntent: 'crypto' },
  { id: 295, category: 'crypto', question: 'Chainlink LINK value', expectedIntent: 'crypto' },
  { id: 296, category: 'crypto', question: 'Uniswap UNI price', expectedIntent: 'crypto' },
  { id: 297, category: 'crypto', question: 'Aave prix', expectedIntent: 'crypto' },
  { id: 298, category: 'crypto', question: 'Polygon MATIC value', expectedIntent: 'crypto' },
  { id: 299, category: 'crypto', question: 'Cosmos ATOM price', expectedIntent: 'crypto' },
  { id: 300, category: 'crypto', question: 'Near Protocol cours', expectedIntent: 'crypto' },
  { id: 301, category: 'crypto', question: 'Bitcoin market cap', expectedIntent: 'crypto' },
  { id: 302, category: 'crypto', question: 'Capitalisation Ethereum', expectedIntent: 'crypto' },
  { id: 303, category: 'crypto', question: 'Top 10 cryptos', expectedIntent: 'crypto' },
  { id: 304, category: 'crypto', question: 'Best performing crypto today', expectedIntent: 'crypto' },
  { id: 305, category: 'crypto', question: 'Crypto qui monte', expectedIntent: 'crypto' },
  { id: 306, category: 'crypto', question: 'Bitcoin 24h change', expectedIntent: 'crypto' },
  { id: 307, category: 'crypto', question: 'ETH weekly performance', expectedIntent: 'crypto' },
  { id: 308, category: 'crypto', question: 'BTC vs ETH', expectedIntent: 'crypto' },
  { id: 309, category: 'crypto', question: 'Stablecoins prices', expectedIntent: 'crypto' },
  { id: 310, category: 'crypto', question: 'USDT USDC comparison', expectedIntent: 'crypto' },
];

// ==========================================
// CATÉGORIE 8: TRANSITIONS IMAGE -> SITE (40)
// ==========================================
const transitionImageToSite: TestQuestion[] = [
  { id: 311, category: 'transition_image_site', question: 'Je ne veux plus d\'images, crée-moi un site web', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 312, category: 'transition_image_site', question: 'Arrête les images, fais-moi un site', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 313, category: 'transition_image_site', question: 'Stop les images, crée un site web', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 314, category: 'transition_image_site', question: 'Plus d\'images, maintenant un site', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 315, category: 'transition_image_site', question: 'No more images, create a website', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 316, category: 'transition_image_site', question: 'Instead of images, build me a site', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true },
  { id: 317, category: 'transition_image_site', question: 'Maintenant je veux un site web', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true },
  { id: 318, category: 'transition_image_site', question: 'Now I want a website', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true },
  { id: 319, category: 'transition_image_site', question: 'Plutôt crée-moi un site', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true },
  { id: 320, category: 'transition_image_site', question: 'Rather build me a website', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true },
  { id: 321, category: 'transition_image_site', question: 'À la place, fais-moi un site web', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true },
  { id: 322, category: 'transition_image_site', question: 'En fait, je préfère un site', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true },
  { id: 323, category: 'transition_image_site', question: 'Actually, create a website instead', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true },
  { id: 324, category: 'transition_image_site', question: 'Finalement, un site web serait mieux', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true },
  { id: 325, category: 'transition_image_site', question: 'Je change d\'avis, crée un site', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true },
  { id: 326, category: 'transition_image_site', question: 'Changed my mind, build a website', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true },
  { id: 327, category: 'transition_image_site', question: 'Oublie les images, fais un site', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 328, category: 'transition_image_site', question: 'Forget the images, create a site', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 329, category: 'transition_image_site', question: 'Laisse tomber les images, je veux un site', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 330, category: 'transition_image_site', question: 'Drop the images, make me a website', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 331, category: 'transition_image_site', question: 'Pas d\'images, un site web s\'il te plaît', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerNegation: true },
  { id: 332, category: 'transition_image_site', question: 'No images, a website please', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerNegation: true },
  { id: 333, category: 'transition_image_site', question: 'Je préfère un site à une image', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true },
  { id: 334, category: 'transition_image_site', question: 'I prefer a website over an image', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true },
  { id: 335, category: 'transition_image_site', question: 'Un site web serait plus utile', expectedIntent: 'site_creation', previousContext: 'image_generation' },
  { id: 336, category: 'transition_image_site', question: 'A website would be more useful', expectedIntent: 'site_creation', previousContext: 'image_generation' },
  { id: 337, category: 'transition_image_site', question: 'Crée plutôt un site pour mon business', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true },
  { id: 338, category: 'transition_image_site', question: 'Build a business website instead', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true },
  { id: 339, category: 'transition_image_site', question: 'Je veux passer à la création de site', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true },
  { id: 340, category: 'transition_image_site', question: 'Let\'s switch to website creation', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true },
  { id: 341, category: 'transition_image_site', question: 'Assez d\'images, passons au site', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 342, category: 'transition_image_site', question: 'Enough images, let\'s do a website', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 343, category: 'transition_image_site', question: 'Terminé avec les images, site web maintenant', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true },
  { id: 344, category: 'transition_image_site', question: 'Done with images, website now', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerTransition: true },
  { id: 345, category: 'transition_image_site', question: 'Les images c\'est fini, crée un site', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerNegation: true },
  { id: 346, category: 'transition_image_site', question: 'Images are done, create a site', expectedIntent: 'site_creation', previousContext: 'image_generation' },
  { id: 347, category: 'transition_image_site', question: 'Je n\'ai plus besoin d\'images, mais d\'un site', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerNegation: true },
  { id: 348, category: 'transition_image_site', question: 'I don\'t need images anymore, but a website', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerNegation: true },
  { id: 349, category: 'transition_image_site', question: 'Annule les images et crée un site', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerNegation: true },
  { id: 350, category: 'transition_image_site', question: 'Cancel images and create a website', expectedIntent: 'site_creation', previousContext: 'image_generation', shouldTriggerNegation: true },
];

// ==========================================
// CATÉGORIE 9: TRANSITIONS SITE -> APP (40)
// ==========================================
const transitionSiteToApp: TestQuestion[] = [
  { id: 351, category: 'transition_site_app', question: 'Je ne veux plus de site, crée-moi une application', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 352, category: 'transition_site_app', question: 'Arrête le site, fais-moi une app', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 353, category: 'transition_site_app', question: 'Stop the website, create an app', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 354, category: 'transition_site_app', question: 'Plus de site, maintenant une application', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 355, category: 'transition_site_app', question: 'No more website, build an application', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 356, category: 'transition_site_app', question: 'Instead of a site, create a chatbot', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true },
  { id: 357, category: 'transition_site_app', question: 'Maintenant je veux une vraie application', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true },
  { id: 358, category: 'transition_site_app', question: 'Now I want a real application', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true },
  { id: 359, category: 'transition_site_app', question: 'Plutôt crée-moi un chatbot', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true },
  { id: 360, category: 'transition_site_app', question: 'Rather build me an AI agent', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true },
  { id: 361, category: 'transition_site_app', question: 'À la place, fais-moi une application', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true },
  { id: 362, category: 'transition_site_app', question: 'En fait, je préfère une app', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true },
  { id: 363, category: 'transition_site_app', question: 'Actually, create an application instead', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true },
  { id: 364, category: 'transition_site_app', question: 'Finalement, une application serait mieux', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true },
  { id: 365, category: 'transition_site_app', question: 'Je change d\'avis, crée un chatbot', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true },
  { id: 366, category: 'transition_site_app', question: 'Changed my mind, build an app', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true },
  { id: 367, category: 'transition_site_app', question: 'Oublie le site, fais une application', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 368, category: 'transition_site_app', question: 'Forget the website, create an app', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 369, category: 'transition_site_app', question: 'Laisse tomber le site, je veux une app', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 370, category: 'transition_site_app', question: 'Drop the website, make me an application', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 371, category: 'transition_site_app', question: 'Pas de site, une application s\'il te plaît', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerNegation: true },
  { id: 372, category: 'transition_site_app', question: 'No website, an application please', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerNegation: true },
  { id: 373, category: 'transition_site_app', question: 'Je préfère une app à un site', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true },
  { id: 374, category: 'transition_site_app', question: 'I prefer an app over a website', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true },
  { id: 375, category: 'transition_site_app', question: 'Une application serait plus utile', expectedIntent: 'app_creation', previousContext: 'site_creation' },
  { id: 376, category: 'transition_site_app', question: 'An application would be more useful', expectedIntent: 'app_creation', previousContext: 'site_creation' },
  { id: 377, category: 'transition_site_app', question: 'Crée plutôt un chatbot pour mon business', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true },
  { id: 378, category: 'transition_site_app', question: 'Build a business chatbot instead', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true },
  { id: 379, category: 'transition_site_app', question: 'Je veux passer à la création d\'app', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true },
  { id: 380, category: 'transition_site_app', question: 'Let\'s switch to app creation', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true },
  { id: 381, category: 'transition_site_app', question: 'Assez de sites, passons à l\'application', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 382, category: 'transition_site_app', question: 'Enough websites, let\'s do an app', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 383, category: 'transition_site_app', question: 'Terminé avec le site, application maintenant', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true },
  { id: 384, category: 'transition_site_app', question: 'Done with website, app now', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerTransition: true },
  { id: 385, category: 'transition_site_app', question: 'Le site c\'est fini, crée une app', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerNegation: true },
  { id: 386, category: 'transition_site_app', question: 'Website is done, create an app', expectedIntent: 'app_creation', previousContext: 'site_creation' },
  { id: 387, category: 'transition_site_app', question: 'Je n\'ai plus besoin de site, mais d\'une app', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerNegation: true },
  { id: 388, category: 'transition_site_app', question: 'I don\'t need a website anymore, but an app', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerNegation: true },
  { id: 389, category: 'transition_site_app', question: 'Annule le site et crée une application', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerNegation: true },
  { id: 390, category: 'transition_site_app', question: 'Cancel website and create an application', expectedIntent: 'app_creation', previousContext: 'site_creation', shouldTriggerNegation: true },
];

// ==========================================
// CATÉGORIE 10: TRANSITIONS APP -> CODE (40)
// ==========================================
const transitionAppToCode: TestQuestion[] = [
  { id: 391, category: 'transition_app_code', question: 'Je ne veux plus d\'application, exécute du code', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 392, category: 'transition_app_code', question: 'Arrête l\'app, lance ce script', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 393, category: 'transition_app_code', question: 'Stop the app, run this code', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 394, category: 'transition_app_code', question: 'Plus d\'app, maintenant exécute du code', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 395, category: 'transition_app_code', question: 'No more app, execute code', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 396, category: 'transition_app_code', question: 'Instead of an app, run this script', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true },
  { id: 397, category: 'transition_app_code', question: 'Maintenant je veux exécuter du code', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true },
  { id: 398, category: 'transition_app_code', question: 'Now I want to run code', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true },
  { id: 399, category: 'transition_app_code', question: 'Plutôt exécute ce script Python', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true },
  { id: 400, category: 'transition_app_code', question: 'Rather run this JavaScript', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true },
  { id: 401, category: 'transition_app_code', question: 'À la place, fais tourner ce code', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true },
  { id: 402, category: 'transition_app_code', question: 'En fait, je préfère exécuter du code', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true },
  { id: 403, category: 'transition_app_code', question: 'Actually, execute code instead', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true },
  { id: 404, category: 'transition_app_code', question: 'Finalement, lance ce script', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true },
  { id: 405, category: 'transition_app_code', question: 'Je change d\'avis, exécute du code', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true },
  { id: 406, category: 'transition_app_code', question: 'Changed my mind, run code', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true },
  { id: 407, category: 'transition_app_code', question: 'Oublie l\'app, exécute ce script', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 408, category: 'transition_app_code', question: 'Forget the app, run this code', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 409, category: 'transition_app_code', question: 'Laisse tomber l\'app, je veux du code', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 410, category: 'transition_app_code', question: 'Drop the app, execute code', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 411, category: 'transition_app_code', question: 'Pas d\'app, exécute du code s\'il te plaît', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerNegation: true },
  { id: 412, category: 'transition_app_code', question: 'No app, run code please', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerNegation: true },
  { id: 413, category: 'transition_app_code', question: 'Je préfère exécuter du code', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true },
  { id: 414, category: 'transition_app_code', question: 'I prefer to run code', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true },
  { id: 415, category: 'transition_app_code', question: 'Exécuter du code serait plus utile', expectedIntent: 'code_execution', previousContext: 'app_creation' },
  { id: 416, category: 'transition_app_code', question: 'Running code would be more useful', expectedIntent: 'code_execution', previousContext: 'app_creation' },
  { id: 417, category: 'transition_app_code', question: 'Lance plutôt ce script Python', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true },
  { id: 418, category: 'transition_app_code', question: 'Run this Python script instead', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true },
  { id: 419, category: 'transition_app_code', question: 'Je veux passer à l\'exécution de code', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true },
  { id: 420, category: 'transition_app_code', question: 'Let\'s switch to code execution', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true },
  { id: 421, category: 'transition_app_code', question: 'Assez d\'apps, passons au code', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 422, category: 'transition_app_code', question: 'Enough apps, let\'s do code', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true, shouldTriggerNegation: true },
  { id: 423, category: 'transition_app_code', question: 'Terminé avec l\'app, code maintenant', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true },
  { id: 424, category: 'transition_app_code', question: 'Done with app, code now', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerTransition: true },
  { id: 425, category: 'transition_app_code', question: 'L\'app c\'est fini, exécute du code', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerNegation: true },
  { id: 426, category: 'transition_app_code', question: 'App is done, run code', expectedIntent: 'code_execution', previousContext: 'app_creation' },
  { id: 427, category: 'transition_app_code', question: 'Je n\'ai plus besoin d\'app, mais de code', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerNegation: true },
  { id: 428, category: 'transition_app_code', question: 'I don\'t need an app anymore, but code', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerNegation: true },
  { id: 429, category: 'transition_app_code', question: 'Annule l\'app et exécute ce code', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerNegation: true },
  { id: 430, category: 'transition_app_code', question: 'Cancel app and run this code', expectedIntent: 'code_execution', previousContext: 'app_creation', shouldTriggerNegation: true },
];

// ==========================================
// CATÉGORIE 11: NÉGATIONS ET ARRÊTS (40)
// ==========================================
const negationQuestions: TestQuestion[] = [
  { id: 431, category: 'negation', question: 'Je ne veux plus rien', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 432, category: 'negation', question: 'Arrête tout', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 433, category: 'negation', question: 'Stop everything', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 434, category: 'negation', question: 'Annule', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 435, category: 'negation', question: 'Cancel', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 436, category: 'negation', question: 'Je ne veux plus de génération d\'images', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 437, category: 'negation', question: 'I don\'t want image generation anymore', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 438, category: 'negation', question: 'Arrête de créer des sites', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 439, category: 'negation', question: 'Stop creating websites', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 440, category: 'negation', question: 'Plus d\'applications', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 441, category: 'negation', question: 'No more apps', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 442, category: 'negation', question: 'Arrête d\'exécuter du code', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 443, category: 'negation', question: 'Stop running code', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 444, category: 'negation', question: 'Je ne veux plus de météo', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 445, category: 'negation', question: 'No more weather updates', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 446, category: 'negation', question: 'Arrête les cryptos', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 447, category: 'negation', question: 'Stop crypto prices', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 448, category: 'negation', question: 'Laisse tomber', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 449, category: 'negation', question: 'Forget it', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 450, category: 'negation', question: 'Oublie ce que j\'ai dit', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 451, category: 'negation', question: 'Forget what I said', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 452, category: 'negation', question: 'C\'est bon, arrête', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 453, category: 'negation', question: 'That\'s enough, stop', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 454, category: 'negation', question: 'Ça suffit', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 455, category: 'negation', question: 'Enough', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 456, category: 'negation', question: 'Je n\'en veux plus', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 457, category: 'negation', question: 'I don\'t want any more', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 458, category: 'negation', question: 'Termine', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 459, category: 'negation', question: 'End this', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 460, category: 'negation', question: 'Fini', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 461, category: 'negation', question: 'Done', expectedIntent: 'conversation' },
  { id: 462, category: 'negation', question: 'Je ne suis pas intéressé', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 463, category: 'negation', question: 'I\'m not interested', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 464, category: 'negation', question: 'Pas maintenant', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 465, category: 'negation', question: 'Not now', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 466, category: 'negation', question: 'Plus tard', expectedIntent: 'conversation' },
  { id: 467, category: 'negation', question: 'Later', expectedIntent: 'conversation' },
  { id: 468, category: 'negation', question: 'Je refuse', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 469, category: 'negation', question: 'I refuse', expectedIntent: 'conversation', shouldTriggerNegation: true },
  { id: 470, category: 'negation', question: 'Non merci', expectedIntent: 'conversation', shouldTriggerNegation: true },
];

// ==========================================
// CATÉGORIE 12: RÉFÉRENCES CONTEXTUELLES (30)
// ==========================================
const contextualQuestions: TestQuestion[] = [
  { id: 471, category: 'contextual', question: 'Refais ça', expectedIntent: 'conversation', previousContext: 'image_generation' },
  { id: 472, category: 'contextual', question: 'Do it again', expectedIntent: 'conversation', previousContext: 'image_generation' },
  { id: 473, category: 'contextual', question: 'Le même en bleu', expectedIntent: 'image_generation', previousContext: 'image_generation' },
  { id: 474, category: 'contextual', question: 'Same but in red', expectedIntent: 'image_generation', previousContext: 'image_generation' },
  { id: 475, category: 'contextual', question: 'Celui-ci est parfait', expectedIntent: 'conversation', previousContext: 'image_generation' },
  { id: 476, category: 'contextual', question: 'This one is perfect', expectedIntent: 'conversation', previousContext: 'image_generation' },
  { id: 477, category: 'contextual', question: 'Comme avant', expectedIntent: 'conversation', previousContext: 'site_creation' },
  { id: 478, category: 'contextual', question: 'Like before', expectedIntent: 'conversation', previousContext: 'site_creation' },
  { id: 479, category: 'contextual', question: 'Encore une fois', expectedIntent: 'conversation', previousContext: 'code_execution' },
  { id: 480, category: 'contextual', question: 'One more time', expectedIntent: 'conversation', previousContext: 'code_execution' },
  { id: 481, category: 'contextual', question: 'La même chose', expectedIntent: 'conversation', previousContext: 'weather' },
  { id: 482, category: 'contextual', question: 'The same thing', expectedIntent: 'conversation', previousContext: 'weather' },
  { id: 483, category: 'contextual', question: 'Pareil', expectedIntent: 'conversation', previousContext: 'crypto' },
  { id: 484, category: 'contextual', question: 'Same', expectedIntent: 'conversation', previousContext: 'crypto' },
  { id: 485, category: 'contextual', question: 'Continue', expectedIntent: 'conversation', previousContext: 'site_creation' },
  { id: 486, category: 'contextual', question: 'Keep going', expectedIntent: 'conversation', previousContext: 'app_creation' },
  { id: 487, category: 'contextual', question: 'Plus de détails', expectedIntent: 'conversation', previousContext: 'conversation' },
  { id: 488, category: 'contextual', question: 'More details', expectedIntent: 'conversation', previousContext: 'conversation' },
  { id: 489, category: 'contextual', question: 'Explique mieux', expectedIntent: 'conversation', previousContext: 'conversation' },
  { id: 490, category: 'contextual', question: 'Explain better', expectedIntent: 'conversation', previousContext: 'conversation' },
  { id: 491, category: 'contextual', question: 'Développe', expectedIntent: 'conversation', previousContext: 'conversation' },
  { id: 492, category: 'contextual', question: 'Elaborate', expectedIntent: 'conversation', previousContext: 'conversation' },
  { id: 493, category: 'contextual', question: 'C\'est ça', expectedIntent: 'conversation', previousContext: 'image_generation' },
  { id: 494, category: 'contextual', question: 'That\'s it', expectedIntent: 'conversation', previousContext: 'site_creation' },
  { id: 495, category: 'contextual', question: 'Exactement', expectedIntent: 'conversation', previousContext: 'app_creation' },
  { id: 496, category: 'contextual', question: 'Exactly', expectedIntent: 'conversation', previousContext: 'code_execution' },
  { id: 497, category: 'contextual', question: 'Oui, ça', expectedIntent: 'conversation', previousContext: 'weather' },
  { id: 498, category: 'contextual', question: 'Yes, that', expectedIntent: 'conversation', previousContext: 'crypto' },
  { id: 499, category: 'contextual', question: 'Parfait, garde ça', expectedIntent: 'conversation', previousContext: 'image_generation' },
  { id: 500, category: 'contextual', question: 'Perfect, keep that', expectedIntent: 'conversation', previousContext: 'site_creation' },
];

// ==========================================
// EXPORT DE TOUTES LES QUESTIONS
// ==========================================
export const allTestQuestions: TestQuestion[] = [
  ...conversationQuestions,
  ...imageQuestions,
  ...siteQuestions,
  ...appQuestions,
  ...codeQuestions,
  ...weatherQuestions,
  ...cryptoQuestions,
  ...transitionImageToSite,
  ...transitionSiteToApp,
  ...transitionAppToCode,
  ...negationQuestions,
  ...contextualQuestions,
];

// Statistiques
export const testStats = {
  total: allTestQuestions.length,
  byCategory: {
    conversation: conversationQuestions.length,
    image: imageQuestions.length,
    site: siteQuestions.length,
    app: appQuestions.length,
    code: codeQuestions.length,
    weather: weatherQuestions.length,
    crypto: cryptoQuestions.length,
    transition_image_site: transitionImageToSite.length,
    transition_site_app: transitionSiteToApp.length,
    transition_app_code: transitionAppToCode.length,
    negation: negationQuestions.length,
    contextual: contextualQuestions.length,
  }
};

console.log('Test Questions loaded:', testStats);
